### ISSUE TITLE
Do you plan to make it work with webpack encore?

### ISSUE THREAD

**Issue by bastien70** [SymfonyCasts/tailwind-bundle#24]
Hey ! This bundle is very cool for the Asset Mapper component. But do you plan go make it work with encore ? Or maybe it's already possible no ?

**Comment by weaverryan** [comment]
Hey! 

We won’t make this work for encore - mostly because if you’re using encore / webpack, then you can already set up tailwind in the normal way. This bundle is really about taking the standalone tailwind executable and making it work seamlessly with asset mapper. In encore, use the traditional setup docs for encore from tailwind’s docs. 

Cheers!
